jeffotoni/quick

README.md, quick.go, quick_test.go
- Implementasção de método PUT
- Criação de teste (vazio) para método PUT
- Atualização de roadmap
- Adicionando roadmap de método OPTIONS
=> Método PUT

quick.go, quick_test.go
Criada função que extrai o path e os params de um dado pattern
=> feat: create extractPathPattern function and tests

README.md, quick.go, quick_test.go
Serve Static File implementation
How to use:
```
package main
import "github.com/jeffotoni/quick"
func main() {
app := quick.New()
app.ServeStaticFile("/static")
app.Listen("0.0.0.0:8080")
}
````
And then add the file to the `/static` folder, like `/static/dog.png`
=> serve static file implementation

quick.go
Update notes:
* Fix of route bug that broke when route is only "/" or "/your/path";
* Fixing bug that every route is accepted, and not checked by pattern;
* Updating the way to verify and get route params.
=> updating the route get params and checker if it's valid or not

README.md, quick.go, quick_test.go
Por favor não mergear essa branch ainda, pois falta os testes no POST
=> Improving GET Tests

README.md, quick.go, quick_test.go
Corrigindo alguns bugs e adicionando um "wait" para iniciar o server de teste
=> Improve 16

group_test.go, quick.go, quick_test.go
- Support to regex in route;
Example: /my/route/{[0-9]+}
=> Feature - 23

quick.go, quick_test.go
This method append value to existing header. If header not exists, the `Append` will create it.
=> create ctx method Append

quick.go, quick_ctx_mock.go, quick_ctx_mock_test.go
- Implementing Ctx Mocks to test only the handlers;
- New files called quick_ctx_mock.go and quick_ctx_mock.go;
- Mock JSON and XML handlers;
- Update to 81% the test Coverage.
=> Feature - 26

go.mod
- Bind now can be used by json or xml content type;
- Updating test coverage to 82%.
Closes #49
=> Fix Bug - 49

quick.go
- Fixing param route bug, updating the way to create params map.
Closes #54
=> Fix bug 54

.gitignore, quick.go, quick_test.go
- Updating tests with Use() function and using cors.
Closes #52
=> Improve 52

README.md, group.go, group_test.go, quick.go, quick_test.go, quicktest.go
- feat: implement DELETE method and test
- TODO: error when use DELETE method in `QuickTest" function
- doc: update DELETE status quo
- doc: add CONNECT status quo
Reference:
- https://www.rfc-editor.org/rfc/rfc9110.html#name-delete
-  https://www.rfc-editor.org/rfc/rfc9110.html#name-connect
=> feat DELETE method

README.md
=> fix(README): fixed readme where roadmap list was broken

middleware/compress/compress.go, middleware/compress/compress_test.go
fixing error in compress middleware that was not setting headers properly
#69
=> fix issue 69

quick.go, quick_example_test.go, quick_fileserver_test.go
- Patch
- Option
- extractParamsPatch
- Static
=> adds example go doc in:

README.md, example/middleware/README.md, example/middleware/logger/with.format/main.go, example/middleware/logger/with.json/main.go, example/middleware/logger/with.slog/main.go, middleware/logger/logger.go, middleware/logger/logger_example_test.go
- Added ExampleNew to demonstrate the usage of logger.New().
- Updated the README to include:
- Explanation of the logger middleware.
- Key features and benefits of request logging.
- Three usage examples:
- Text Logging (text format with a custom pattern).
- Structured Logging (slog format for structured output).
- JSON Logging (json format for machine-readable logs).
- cURL commands to test each logging format.
- A comparison table highlighting key differences between log formats.
- Improved code documentation with inline comments.
- Enhanced structured logging support, making logs more readable and customizable.
- Ensured formatting consistency across all logging examples.
=> docs: Add examples, documentation, and structured logging support

middleware/helmet/helmet.go, middleware/helmet/helmet_test.go
Added a Helmet middleware to enhance security by setting important HTTP headers, protecting against common web vulnerabilities such as XSS, Clickjacking, MIME sniffing, and insecure connections.
**Content Security Policy (CSP)** : Restricts resource loading to prevent XSS attacks.
**X-Frame-Options**: Protects against Clickjacking by preventing iframe embedding.
**X-Content-Type-Options** : Prevents MIME-type sniffing attacks.
**X-XSS-Protection** : Enables browser’s built-in XSS filter.
**Strict Transport Security (HSTS)** : Enforces HTTPS for secure communication.
**Referrer-Policy** : Controls how much referrer info is shared.
**Cache-Control** : Prevents sensitive data from being cached.
**X-Powered-By** : Option to remove or customize to prevent exposure of server details.
=> feat: add Helmet middleware to secure http headers

quicktest_example_v2_test.go
added example of new implementations of quick_v2
=> docs:adds example of new quick_v2 implementations

example/site/docs/app/app.go, example/site/docs/ctx/ctx.go, example/site/docs/middleware/CORS.go, example/site/docs/middleware/Healthcheck.go, example/site/docs/middleware/basicauth.go, example/site/docs/middleware/compress.go, example/site/docs/middleware/helmet.go, example/site/docs/middleware/limiter.go, example/site/docs/package-lock.json, http/README.md, http/client/README.md
improving http readme, and adding examples
=> Docs/improving http client readme.md

http/client/client.go
http client max retries value in error return
=> refactor: http client max retries value in error return

CONTRIBUTING.md, example/quick.http.client/README.md, http/README.md
doing a improvement in http readme
=> docs: doing a readme iprovement

README.md
adding a cache example in root readme
=> cache example

README.md
=> Adding cors in readme
